
---
spring:
  config.activate.on-profile: default
  sql.init.platform: h2
# sap.spring.security.identity.prooftoken: false
cds:
  data-source.auto-config.enabled: false
---
management:
  endpoint:
    health:
      show-components: always
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,db
  endpoints:
    web:
      exposure:
        include: health
  health:
    defaults:
      enabled: false
    ping:
      enabled: true
    db:
      enabled: true
